trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: KafkaDeployment7.9.0
  displayName: KafkaDeployment7.9.0
  jobs:
  - deployment: KafkaDeployment7.9.0
    displayName: KafkaDeployment7.9.0
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                if [[ -z `/bin/bash -c "helm repo list | grep confluentinc | cut -f1"` ]]
                then
                  helm repo add confluentinc https://packages.confluent.io/helm
                  helm repo update
                fi
                yes|argocd login argocd.singhritesh85.com --username admin --password $(ARGOCD_PASSWORD) --grpc-web
                argocd repo add https://github.com/singhritesh85/confluent-kubernetes.git --username $(GITHUB_USERNAME) --password $(GITHUB_PASSWORD)
                argocd app create kafka-with-kraft --project default --repo https://github.com/singhritesh85/confluent-kubernetes.git --path ./confluent-kafka-7.9.0 --dest-namespace confluent --sync-option CreateNamespace=true --dest-server https://kubernetes.default.svc --sync-policy automated --upsert
                #argocd app sync kafka-with-kraft
                kubectl get pods -n confluent
                kubectl get svc -n confluent
                argocd app create kafka-topic --project default --repo https://github.com/singhritesh85/confluent-kubernetes.git --path ./confluent-kafka-topic --dest-namespace confluent --sync-option CreateNamespace=true --dest-server https://kubernetes.default.svc --sync-policy automated --upsert
                #argocd app sync kafka-topic