apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - confluent
  selector:
    matchLabels:
      type: kafka
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  replicas: 1
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: default
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
  receivers:
  - name: default
